
#RUN FIRST AND THEN APPLY CLUSTER ROLEBINDING
#kubectl create serviceaccount curl-sa

apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: curl-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: curl-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  labels:
    app: curl-test
spec:
  serviceAccountName: curl-sa
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sh"]
    args: ["-c", "while true; do sleep 3600; done"] # Infinite loop to keep the pod running
  restartPolicy: Always
