apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "confluence"
        - name: POSTGRES_USER
          value: "confluence"
        - name: POSTGRES_PASSWORD
          value: "password"
